env: "local"
storage_path: "user=postgres password=postgres dbname=postgres sslmode=disable port=5010"
kafka_path: ":9093"
http_server:
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 60s
kafka_cfg:
  kafka_URL: "localhost:9093"
  kafka_producer_topic: "FIOfailed"
  kafka_consumer_topic: "FIO"
  kafka_delay_ms: "5"
  kafka_consumer_groupID: "0"
enrichment_URLs: [
  "https://api.genderize.io",
	"https://api.agify.io",
	"https://api.nationalize.io"
]
enrichment_timeout_ms: "1"
redis_cfg:
  redis_URL: "localhost:6379"
  ttl: 60m
